/*
 * This file was automatically generated by EvoSuite
 * Thu Oct 19 23:53:47 GMT 2023
 */

package org.apache.commons.net.bsd;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.net.bsd.RLoginClient;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RLoginClient_ESTest extends RLoginClient_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RLoginClient rLoginClient0 = new RLoginClient();
      // Undeclared exception!
      try { 
        rLoginClient0.rlogin("Security violation: unexpected connection attempt by ", (String) null, (String) null, 0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.bsd.RExecClient", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      RLoginClient rLoginClient0 = new RLoginClient();
      // Undeclared exception!
      try { 
        rLoginClient0.rlogin("_V-", "_V-", "V$viNujrqA");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.bsd.RExecClient", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      RLoginClient rLoginClient0 = new RLoginClient();
      // Undeclared exception!
      try { 
        rLoginClient0.rlogin("e!Z7O9", "PfV+,\"_", "PfV+,\"_");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.bsd.RExecClient", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      RLoginClient rLoginClient0 = new RLoginClient();
      // Undeclared exception!
      try { 
        rLoginClient0.rlogin("l\b*?Ms", "l\b*?Ms", "y~}d{TOh", 1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.bsd.RExecClient", e);
      }
  }
}
