/*
 * This file was automatically generated by EvoSuite
 * Thu Oct 19 21:39:03 GMT 2023
 */

package org.apache.commons.net.ftp;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.net.InetAddress;
import java.net.ServerSocket;
import javax.net.ssl.SSLContext;
import org.apache.commons.net.ftp.FTPSServerSocketFactory;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FTPSServerSocketFactory_ESTest extends FTPSServerSocketFactory_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FTPSServerSocketFactory fTPSServerSocketFactory0 = new FTPSServerSocketFactory((SSLContext) null);
      // Undeclared exception!
      try { 
        fTPSServerSocketFactory0.createServerSocket((-796), (-796));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.ftp.FTPSServerSocketFactory", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      FTPSServerSocketFactory fTPSServerSocketFactory0 = new FTPSServerSocketFactory((SSLContext) null);
      // Undeclared exception!
      try { 
        fTPSServerSocketFactory0.init((ServerSocket) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.ftp.FTPSServerSocketFactory", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SSLContext sSLContext0 = mock(SSLContext.class, new ViolatedAssumptionAnswer());
      FTPSServerSocketFactory fTPSServerSocketFactory0 = new FTPSServerSocketFactory(sSLContext0);
      // Undeclared exception!
      try { 
        fTPSServerSocketFactory0.createServerSocket((-55), (-55), (InetAddress) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("javax.net.ssl.SSLContext", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      SSLContext sSLContext0 = mock(SSLContext.class, new ViolatedAssumptionAnswer());
      FTPSServerSocketFactory fTPSServerSocketFactory0 = new FTPSServerSocketFactory(sSLContext0);
      // Undeclared exception!
      try { 
        fTPSServerSocketFactory0.createServerSocket();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("javax.net.ssl.SSLContext", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      SSLContext sSLContext0 = mock(SSLContext.class, new ViolatedAssumptionAnswer());
      FTPSServerSocketFactory fTPSServerSocketFactory0 = new FTPSServerSocketFactory(sSLContext0);
      // Undeclared exception!
      try { 
        fTPSServerSocketFactory0.createServerSocket(0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("javax.net.ssl.SSLContext", e);
      }
  }
}
