/*
 * This file was automatically generated by EvoSuite
 * Thu Oct 19 22:10:43 GMT 2023
 */

package org.apache.commons.net.io;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.OutputStream;
import java.net.Socket;
import org.apache.commons.net.io.SocketOutputStream;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SocketOutputStream_ESTest extends SocketOutputStream_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Socket socket0 = mock(Socket.class, new ViolatedAssumptionAnswer());
      OutputStream outputStream0 = mock(OutputStream.class, new ViolatedAssumptionAnswer());
      SocketOutputStream socketOutputStream0 = new SocketOutputStream(socket0, outputStream0);
      socketOutputStream0.close();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Socket socket0 = mock(Socket.class, new ViolatedAssumptionAnswer());
      SocketOutputStream socketOutputStream0 = new SocketOutputStream(socket0, (OutputStream) null);
      byte[] byteArray0 = new byte[3];
      // Undeclared exception!
      try { 
        socketOutputStream0.write(byteArray0, (int) (byte)0, (int) (byte) (-119));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.io.SocketOutputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Socket socket0 = mock(Socket.class, new ViolatedAssumptionAnswer());
      OutputStream outputStream0 = mock(OutputStream.class, new ViolatedAssumptionAnswer());
      SocketOutputStream socketOutputStream0 = new SocketOutputStream(socket0, outputStream0);
      byte[] byteArray0 = new byte[7];
      socketOutputStream0.write(byteArray0, 0, (int) (byte) (-65));
      assertArrayEquals(new byte[] {(byte)0, (byte)0, (byte)0, (byte)0, (byte)0, (byte)0, (byte)0}, byteArray0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      OutputStream outputStream0 = mock(OutputStream.class, new ViolatedAssumptionAnswer());
      SocketOutputStream socketOutputStream0 = new SocketOutputStream((Socket) null, outputStream0);
      // Undeclared exception!
      try { 
        socketOutputStream0.close();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.net.io.SocketOutputStream", e);
      }
  }
}
